language: python
python:
  - "3.5"
  - "3.6"
addons:
  apt:
    packages:
      - libsndfile1
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
install:
  - pip install .
  - pip install scipy
  - pip install numpy
  - pip install -r extended_requirements.txt
script:
  - py.test sigfeat/tests/ --cov=sigfeat/tests --cov-report term-missing
after_success:
    - coveralls
